"""Technical-lens models plus compatibility exports of shared contracts.

Shared contract classes are defined only in :mod:`protocols`. They remain
re-exported here temporarily so existing Technical Trader integrations do not
break during migration.
"""

from protocols import (
    BacktestInterpretationDraft,
    BacktestPlan,
    BacktestPlanDraft,
    BacktestRequest,
    BacktestResult,
    BacktestStatus,
    CandidateProposalDraft,
    CandidateRuleDraft,
    CandidateRuleSpecification,
    ConfidenceAssessment,
    ConfidenceLevel,
    ConstraintCheckStatus,
    DataArtifact,
    DataCategory,
    DataFieldRequirement,
    DataProvenance,
    DataRequest,
    DataResponse,
    DataUsageSummary,
    MandateConstraintAssessment,
    MandateReference,
    MetricInterpretation,
    PMMandate,
    ResearchExecutionContext,
    RunStatus,
    SpecialistId,
    TaskLineage,
    TraderFailure,
    TraderResearchPlanDraft,
    TraderStrategyPackage,
    TraderTask,
    ValidationSplit,
)

from .hireability import technical_trader_agent_card
from .opportunity_selection import (
    OpportunityCandidateProposalDraft,
    OpportunityCandidateRuleDraft,
    OpportunityPortfolioSelectionDraft,
    OpportunitySleeveParametersDraft,
    OpportunitySleeveSelectionDraft,
    TARGET_TECHNICAL_SLEEVES,
    TechnicalBacktestPlanSelectionDraft,
    TechnicalTransactionCostAssumptionsDraft,
)
from .technical_analysis import (
    AssetTechnicalAnalysis,
    ChartPatternConfig,
    ChartPatternObservation,
    ChartPatternStatus,
    ChartPatternType,
    MovingAverageConfig,
    MovingAverageCrossDirection,
    MovingAverageObservation,
    MovingAverageRelationship,
    PatternPoint,
    PivotKind,
    PriceBar,
    PriceLevelKind,
    PriceSeries,
    SupportResistanceConfig,
    SupportResistanceLevel,
    TechnicalAnalysisReport,
    TechnicalHorizonContext,
    TechnicalOpportunity,
    VolumeAnalysisConfig,
    VolumeObservation,
)

# Former Technical-only names now point at the canonical shared enums.
TraderRunStatus = RunStatus
TraderType = SpecialistId

__all__ = [
    "AssetTechnicalAnalysis",
    "BacktestInterpretationDraft",
    "BacktestPlan",
    "BacktestPlanDraft",
    "BacktestRequest",
    "BacktestResult",
    "BacktestStatus",
    "CandidateProposalDraft",
    "CandidateRuleDraft",
    "CandidateRuleSpecification",
    "ChartPatternConfig",
    "ChartPatternObservation",
    "ChartPatternStatus",
    "ChartPatternType",
    "MovingAverageConfig",
    "MovingAverageCrossDirection",
    "MovingAverageObservation",
    "MovingAverageRelationship",
    "OpportunityCandidateProposalDraft",
    "OpportunityCandidateRuleDraft",
    "OpportunityPortfolioSelectionDraft",
    "OpportunitySleeveParametersDraft",
    "OpportunitySleeveSelectionDraft",
    "ConfidenceAssessment",
    "ConfidenceLevel",
    "ConstraintCheckStatus",
    "DataArtifact",
    "DataCategory",
    "DataFieldRequirement",
    "DataProvenance",
    "DataRequest",
    "DataResponse",
    "DataUsageSummary",
    "MandateConstraintAssessment",
    "MandateReference",
    "MetricInterpretation",
    "PMMandate",
    "PatternPoint",
    "PivotKind",
    "PriceBar",
    "PriceLevelKind",
    "PriceSeries",
    "ResearchExecutionContext",
    "RunStatus",
    "SpecialistId",
    "SupportResistanceConfig",
    "SupportResistanceLevel",
    "TaskLineage",
    "TARGET_TECHNICAL_SLEEVES",
    "TechnicalAnalysisReport",
    "TechnicalBacktestPlanSelectionDraft",
    "TechnicalHorizonContext",
    "TechnicalOpportunity",
    "TechnicalTransactionCostAssumptionsDraft",
    "VolumeAnalysisConfig",
    "VolumeObservation",
    "TraderFailure",
    "TraderResearchPlanDraft",
    "TraderRunStatus",
    "TraderStrategyPackage",
    "TraderTask",
    "TraderType",
    "ValidationSplit",
    "technical_trader_agent_card",
]
