"""
Reporting Agent implementation.

Tasks:
- Collect surviving candidates from RiskReviewResponse
- Build cross-lens comparison
- Generate PM-facing strategy memo using model_client
- Construct ReportingOutput
"""

from .reporting_agent import ReportingAgent
from protocols.reporting import ReportingOutput, ReportingRequest

from pydantic import BaseModel

from agents.technical_trader.model_client import (
    ModelClient,
    ModelRequestContext,
)

REPORT_AGENT_ID = "report_agent"
REPORT_AGENT_CARD_VERSION = "0.1.0"

MEMO_PROMPT_BUILDING_LINES = """
Prepare a PM-facing strategy memo for the surviving candidates.

Candidate comparison:
"""

MEMO_PROMPT_BUILDING_EXTEND = """
Compare the surviving candidates across their different research lenses. 
Explain the important differences in performance, interpretation, strengths, weaknesses, and risk findings. 
Include all required Risk disclosures. 
Do not select a winner or make the final portfolio decision.
"""

REPORTING_SYSTEM_PROMPT = """
You are the Reporting Agent on an investment-research desk.

Prepare a concise strategy memo for the Portfolio Manager based only on
the provided candidate and Risk review information.

Rules:
1. Summarize and compare the surviving strategy candidates.
2. Clearly report material Risk flags and critiques.
3. Do not invent evidence, metrics, or conclusions.
4. Do not select a winner or make the final portfolio decision.
5. Format the memo with a short paragraph per candidate (separated by a
   blank line), followed by a separate paragraph for risk disclosures.
   Do not write it as a single dense block of text.
6. The exact metrics (returns, Sharpe ratio, drawdown, trade counts) are
   already shown in a separate comparison table. Do not restate raw
   numbers in the memo. Instead, focus on what they mean: which candidate
   looks stronger and why, notable strengths or weaknesses, and anything
   a PM should know before deciding -- in plain, textual terms.
"""


class StrategyMemo(BaseModel):
    summary: str


class ReportingAgentImpl(ReportingAgent):

    agent_id = "reporting_agent"

    def __init__(
        self,
        *,
        model_client: ModelClient | None = None,
    ) -> None:
        self._model_client = model_client

    async def report(self, request: ReportingRequest) -> ReportingOutput:

        candidates = self._collect_candidates(request)

        comparison = self._build_comparison(candidates, request.risk_response)

        memo = await self._generate_memo(candidates, comparison, request.risk_response)

        return ReportingOutput(
            output_id=f"{request.request_id}",  # TODO
            request_id=request.request_id,
            surviving_candidate_ids=list(
                candidate.candidate_id
                for candidate in candidates
                if candidate.candidate_id is not None
            ),
            strategy_memo_reference=memo,
            comparison=comparison,
            combination_logic_implemented=False,  # Reporting Agent cannot modify strategies generated by Risk Agent. Report only.
        )

    """1. Risk survivor documentation"""

    def _collect_candidates(self, request: ReportingRequest):
        return request.surviving_candidates

    """2. Cross lens comparison"""

    def _build_comparison(self, candidates, risk_response):
        comparison = {}

        # Tasks:
        # 1. collect key information from each candidate
        # 2. attach relevant risk review information
        # 3. organize candidates into a common comparison structure

        decisions_by_candidate = {
            decision.candidate_id: decision for decision in risk_response.decisions
        }

        candidate_comparisons = []

        for candidate in candidates:
            decision = decisions_by_candidate.get(candidate.candidate_id)
            backtest_result = candidate.backtest_result
            interpretation = candidate.interpretation

            candidate_comparisons.append(
                {
                    "candidate_id": candidate.candidate_id,
                    "trader_id": candidate.trader_id,
                    "hypothesis": candidate.hypothesis,
                    "metrics": (
                        backtest_result.metrics if backtest_result is not None else {}
                    ),
                    "out_of_sample_metrics": (
                        backtest_result.out_of_sample_metrics
                        if backtest_result is not None
                        else {}
                    ),
                    "interpretation": (
                        interpretation.summary if interpretation is not None else None
                    ),
                    "strengths": (
                        interpretation.strengths if interpretation is not None else []
                    ),
                    "weaknesses": (
                        interpretation.weaknesses if interpretation is not None else []
                    ),
                    "risk_verdict": (
                        decision.verdict if decision is not None else None
                    ),
                    "risk_critiques": (
                        decision.critiques if decision is not None else []
                    ),
                    "reporting_flags": (
                        decision.reporting_flags if decision is not None else []
                    ),
                }
            )

        return {
            "candidates": candidate_comparisons,
            "collective_critiques": risk_response.collective_critiques,
            "reporting_required_flags": list(risk_response.required_reporting_flags()),
        }

    """3. Strategy memo generation"""

    def _build_memo_prompt(self, candidates, comparison, risk_response):

        # Task: Build a PM-facing prompt for model_client
        # from the comparison and required risk disclosures

        lines = [MEMO_PROMPT_BUILDING_LINES]

        for candidate in comparison.get("candidates", []):
            lines.extend(
                [
                    "",
                    f"Candidate {candidate.get('candidate_id')}:"
                    f"  Trader_ID: {candidate.get('trader_id')}"
                    f"  Hypothesis: {candidate.get('hypothesis')}"
                    f"  Metrics: {candidate.get('metrics',{})}",
                    (
                        "   Out-of-sample metrics: "
                        f"{candidate.get('out_of_sample_metrics',{})}"
                    ),
                    f"  Interpretation: {candidate.get('interpretation')}",
                    f"  Strengths: {candidate.get('strengths', [])}",
                    f"  Weaknesses: {candidate.get('weaknesses', [])}",
                    f"  Risk verdict: {candidate.get('risk_verdict')}",
                    f"  Risk critiques: {candidate.get('risk_critiques', [])}",
                    f"  Reporting flags: {candidate.get('reporting_flags', [])}",
                ]
            )

        lines.extend(
            [
                "",
                "Round-level risk information:",
                (
                    "Collective critiques: "
                    f"{comparison.get('collective_critiques', [])}"
                ),
                (
                    "Required reporting flags: "
                    f"{comparison.get('reporting_required_flags', [])}"
                ),
                "",
                MEMO_PROMPT_BUILDING_EXTEND,
            ]
        )

        return "\n".join(lines)

    async def _generate_memo(self, candidates, comparison, risk_response):
        # Task: Generate a PM-facing strategy memo

        prompt = self._build_memo_prompt(candidates, comparison, risk_response)

        if self._model_client is None:
            return None

        if not candidates:
            return None

        context = ModelRequestContext(
            agent_id=self.agent_id,
            operation="strategy_memo_generation",
            workflow_id=candidates[0].lineage.workflow_id,
            task_id=risk_response.request_id,
        )

        system_prompt = REPORTING_SYSTEM_PROMPT

        user_prompt = self._build_memo_prompt(candidates, comparison, risk_response)

        result = await self._model_client.generate_structured(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            response_model=StrategyMemo,
            context=context,
        )

        output = result.output

        if isinstance(output, StrategyMemo):
            return output.summary

        return StrategyMemo.model_validate(output).summary
