"""Hireable Technical Trader with replaceable integration interfaces."""

from . import models as _models
from .agents import BaseAgent, StagedTraderAgent, TechnicalTraderAgent
from .adapters import (
    AnthropicTechnicalModelClient,
    OpenAIOutputMode,
    OpenAITechnicalModelClient,
    TechnicalModelConfigurationError,
    TechnicalModelProvider,
    create_technical_model_client_from_env,
)
from .benchmark import BenchmarkComparison, BenchmarkSelectionPolicy
from .diagnostics import (
    InMemoryTechnicalDiagnosticsSink,
    JsonFileTechnicalDiagnosticsSink,
    NullTechnicalDiagnosticsSink,
    TechnicalCandidateDiagnostic,
    TechnicalDiagnosticsSink,
)
from .errors import (
    AgentInputValidationError,
    AgentOutputValidationError,
    AgentTimeoutError,
    MandateValidationError,
    ModelInvocationError,
    ModelTimeoutError,
    ServiceContractError,
    TechnicalAnalysisInputError,
    TechnicalTraderError,
    StructuredOutputValidationError,
)
from .execution import (
    DEFAULT_BACKTEST_TIMEOUT_SECONDS,
    DEFAULT_DATA_SERVICE_TIMEOUT_SECONDS,
    DEFAULT_MODEL_CALL_TIMEOUT_SECONDS,
    DEFAULT_TRADER_TIMEOUT_SECONDS,
    MAX_TRADER_TIMEOUT_SECONDS,
    MAX_TIMEOUT_SECONDS,
    ExecutionPolicy,
)
from .executors import (
    BENCHMARK_FALLBACK_EXECUTOR_ID,
    HEAD_PATTERN_EXECUTOR_ID,
    HORIZON_ADAPTIVE_TREND_EXECUTOR_ID,
    INVERSE_PATTERN_EXECUTOR_ID,
    LONG_ONLY_TECHNICAL_EXECUTORS,
    MOVING_AVERAGE_TREND_EXECUTOR_ID,
    MULTI_ASSET_PORTFOLIO_EXECUTOR_ID,
    RESISTANCE_BREAKOUT_EXECUTOR_ID,
    ROLLING_RESISTANCE_BREAKOUT_EXECUTOR_ID,
    ROLLING_SUPPORT_REACTION_EXECUTOR_ID,
    ROLLING_VOLUME_BREAKOUT_EXECUTOR_ID,
    SUPPORT_REACTION_EXECUTOR_ID,
    TECHNICAL_EXECUTOR_SPECS,
    TECHNICAL_STRATEGY_EXECUTORS,
    TARGET_PORTFOLIO_ASSET_COUNT,
    VOLUME_BREAKOUT_EXECUTOR_ID,
    benchmark_fallback_executor,
    multi_asset_technical_portfolio_executor,
)
from .model_client import (
    InMemoryMetricsSink,
    MetricsSink,
    ModelCallMetrics,
    ModelCallResult,
    ModelCallStatus,
    ModelClient,
    ModelRequestContext,
    ModelUsage,
    NullMetricsSink,
)
from .prompts import (
    DEFAULT_CANDIDATE_PROMPT_ASSETS,
    MAX_CANDIDATE_PROMPT_ASSETS,
    MIN_CANDIDATE_PROMPT_ASSETS,
    compact_horizon_technical_report,
)
from .models import *  # noqa: F403
from .runtime import (
    TechnicalTraderRuntime,
    create_technical_trader_runtime,
    make_langgraph_node,
)
from .horizon import (
    HorizonEvaluationWindow,
    TechnicalHorizonProfile,
    resolve_technical_horizon,
    screen_horizon_opportunities,
    validate_horizon_evaluation_window,
)
from .services import BacktestEngine, DataService, ValidationSplitPolicy
from .tools import (
    ArtifactPayloadTechnicalInputAdapter,
    DeterministicTechnicalAnalysisToolkit,
    TechnicalAnalysisInputAdapter,
    TechnicalAnalysisToolkit,
)

__all__ = [
    *_models.__all__,
    "AgentInputValidationError",
    "AgentOutputValidationError",
    "AgentTimeoutError",
    "AnthropicTechnicalModelClient",
    "ArtifactPayloadTechnicalInputAdapter",
    "BENCHMARK_FALLBACK_EXECUTOR_ID",
    "BacktestEngine",
    "BaseAgent",
    "BenchmarkComparison",
    "BenchmarkSelectionPolicy",
    "DEFAULT_BACKTEST_TIMEOUT_SECONDS",
    "DEFAULT_CANDIDATE_PROMPT_ASSETS",
    "DEFAULT_DATA_SERVICE_TIMEOUT_SECONDS",
    "DEFAULT_MODEL_CALL_TIMEOUT_SECONDS",
    "DEFAULT_TRADER_TIMEOUT_SECONDS",
    "DataService",
    "DeterministicTechnicalAnalysisToolkit",
    "ExecutionPolicy",
    "HEAD_PATTERN_EXECUTOR_ID",
    "HORIZON_ADAPTIVE_TREND_EXECUTOR_ID",
    "HorizonEvaluationWindow",
    "InMemoryTechnicalDiagnosticsSink",
    "INVERSE_PATTERN_EXECUTOR_ID",
    "InMemoryMetricsSink",
    "MAX_TIMEOUT_SECONDS",
    "MAX_TRADER_TIMEOUT_SECONDS",
    "MAX_CANDIDATE_PROMPT_ASSETS",
    "MIN_CANDIDATE_PROMPT_ASSETS",
    "LONG_ONLY_TECHNICAL_EXECUTORS",
    "JsonFileTechnicalDiagnosticsSink",
    "MOVING_AVERAGE_TREND_EXECUTOR_ID",
    "MULTI_ASSET_PORTFOLIO_EXECUTOR_ID",
    "MandateValidationError",
    "MetricsSink",
    "ModelCallMetrics",
    "ModelCallResult",
    "ModelCallStatus",
    "ModelClient",
    "ModelInvocationError",
    "ModelRequestContext",
    "ModelTimeoutError",
    "ModelUsage",
    "NullMetricsSink",
    "NullTechnicalDiagnosticsSink",
    "OpenAIOutputMode",
    "OpenAITechnicalModelClient",
    "RESISTANCE_BREAKOUT_EXECUTOR_ID",
    "ROLLING_RESISTANCE_BREAKOUT_EXECUTOR_ID",
    "ROLLING_SUPPORT_REACTION_EXECUTOR_ID",
    "ROLLING_VOLUME_BREAKOUT_EXECUTOR_ID",
    "ServiceContractError",
    "StagedTraderAgent",
    "StructuredOutputValidationError",
    "SUPPORT_REACTION_EXECUTOR_ID",
    "TECHNICAL_EXECUTOR_SPECS",
    "TECHNICAL_STRATEGY_EXECUTORS",
    "TARGET_PORTFOLIO_ASSET_COUNT",
    "TechnicalAnalysisInputAdapter",
    "TechnicalAnalysisInputError",
    "TechnicalAnalysisToolkit",
    "TechnicalCandidateDiagnostic",
    "TechnicalDiagnosticsSink",
    "TechnicalModelConfigurationError",
    "TechnicalModelProvider",
    "TechnicalTraderAgent",
    "TechnicalTraderError",
    "TechnicalTraderRuntime",
    "TechnicalHorizonProfile",
    "ValidationSplitPolicy",
    "VOLUME_BREAKOUT_EXECUTOR_ID",
    "benchmark_fallback_executor",
    "create_technical_model_client_from_env",
    "compact_horizon_technical_report",
    "create_technical_trader_runtime",
    "make_langgraph_node",
    "multi_asset_technical_portfolio_executor",
    "resolve_technical_horizon",
    "screen_horizon_opportunities",
    "validate_horizon_evaluation_window",
]
