"""Shared numeric limits for model drafts and deterministic executors."""

MIN_TECHNICAL_BUFFER_PERCENT = 0.0
MAX_TECHNICAL_BUFFER_PERCENT = 0.25
MIN_RELATIVE_VOLUME_MULTIPLE = 1.0
MAX_RELATIVE_VOLUME_MULTIPLE = 10.0


__all__ = [
    "MAX_RELATIVE_VOLUME_MULTIPLE",
    "MAX_TECHNICAL_BUFFER_PERCENT",
    "MIN_RELATIVE_VOLUME_MULTIPLE",
    "MIN_TECHNICAL_BUFFER_PERCENT",
]
