"""Deterministic shared backtesting interfaces and implementation."""

from .backtest_engine import (
    BacktestArtifactSink,
    BacktestArtifacts,
    BacktestConfigurationError,
    BacktestDataError,
    BacktestDataResolver,
    BacktestEngine,
    BacktestEngineError,
    BacktestExecutionError,
    DeterministicBacktestEngine,
    EquityPoint,
    ExecutionAssumptions,
    FunctionalStrategyExecutor,
    PriceBar,
    ResolvedBacktestData,
    StrategyEvaluationContext,
    StrategyExecutor,
    StrategySession,
    Transaction,
)

__all__ = [
    "BacktestArtifactSink",
    "BacktestArtifacts",
    "BacktestConfigurationError",
    "BacktestDataError",
    "BacktestDataResolver",
    "BacktestEngine",
    "BacktestEngineError",
    "BacktestExecutionError",
    "DeterministicBacktestEngine",
    "EquityPoint",
    "ExecutionAssumptions",
    "FunctionalStrategyExecutor",
    "PriceBar",
    "ResolvedBacktestData",
    "StrategyEvaluationContext",
    "StrategyExecutor",
    "StrategySession",
    "Transaction",
]
